// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: extra.proto

package syncproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendTabToSelfSpecifics struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	Title                          []byte                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Url                            []byte                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	SharedTimeUsec                 int64                  `protobuf:"varint,3,opt,name=shared_time_usec,json=sharedTimeUsec,proto3" json:"shared_time_usec,omitempty"`
	DeviceName                     []byte                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	Guid                           []byte                 `protobuf:"bytes,5,opt,name=guid,proto3" json:"guid,omitempty"`
	TargetDeviceSyncCacheGuid      []byte                 `protobuf:"bytes,7,opt,name=target_device_sync_cache_guid,json=targetDeviceSyncCacheGuid,proto3" json:"target_device_sync_cache_guid,omitempty"`
	NotificationDismissed          bool                   `protobuf:"varint,8,opt,name=notification_dismissed,json=notificationDismissed,proto3" json:"notification_dismissed,omitempty"`
	Opened                         bool                   `protobuf:"varint,9,opt,name=opened,proto3" json:"opened,omitempty"`
	ReceivedTimeWindowsEpochMicros int64                  `protobuf:"varint,13,opt,name=received_time_windows_epoch_micros,json=receivedTimeWindowsEpochMicros,proto3" json:"received_time_windows_epoch_micros,omitempty"`
	OpenedTimeWindowsEpochMicros   int64                  `protobuf:"varint,14,opt,name=opened_time_windows_epoch_micros,json=openedTimeWindowsEpochMicros,proto3" json:"opened_time_windows_epoch_micros,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *SendTabToSelfSpecifics) Reset() {
	*x = SendTabToSelfSpecifics{}
	mi := &file_extra_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTabToSelfSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTabToSelfSpecifics) ProtoMessage() {}

func (x *SendTabToSelfSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTabToSelfSpecifics.ProtoReflect.Descriptor instead.
func (*SendTabToSelfSpecifics) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{0}
}

func (x *SendTabToSelfSpecifics) GetTitle() []byte {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *SendTabToSelfSpecifics) GetUrl() []byte {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *SendTabToSelfSpecifics) GetSharedTimeUsec() int64 {
	if x != nil {
		return x.SharedTimeUsec
	}
	return 0
}

func (x *SendTabToSelfSpecifics) GetDeviceName() []byte {
	if x != nil {
		return x.DeviceName
	}
	return nil
}

func (x *SendTabToSelfSpecifics) GetGuid() []byte {
	if x != nil {
		return x.Guid
	}
	return nil
}

func (x *SendTabToSelfSpecifics) GetTargetDeviceSyncCacheGuid() []byte {
	if x != nil {
		return x.TargetDeviceSyncCacheGuid
	}
	return nil
}

func (x *SendTabToSelfSpecifics) GetNotificationDismissed() bool {
	if x != nil {
		return x.NotificationDismissed
	}
	return false
}

func (x *SendTabToSelfSpecifics) GetOpened() bool {
	if x != nil {
		return x.Opened
	}
	return false
}

func (x *SendTabToSelfSpecifics) GetReceivedTimeWindowsEpochMicros() int64 {
	if x != nil {
		return x.ReceivedTimeWindowsEpochMicros
	}
	return 0
}

func (x *SendTabToSelfSpecifics) GetOpenedTimeWindowsEpochMicros() int64 {
	if x != nil {
		return x.OpenedTimeWindowsEpochMicros
	}
	return 0
}

type SyncSendTabToSelf struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	SendTabToSelf *SendTabToSelfSpecifics `protobuf:"bytes,601980,opt,name=send_tab_to_self,json=sendTabToSelf,proto3" json:"send_tab_to_self,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSendTabToSelf) Reset() {
	*x = SyncSendTabToSelf{}
	mi := &file_extra_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSendTabToSelf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSendTabToSelf) ProtoMessage() {}

func (x *SyncSendTabToSelf) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSendTabToSelf.ProtoReflect.Descriptor instead.
func (*SyncSendTabToSelf) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{1}
}

func (x *SyncSendTabToSelf) GetSendTabToSelf() *SendTabToSelfSpecifics {
	if x != nil {
		return x.SendTabToSelf
	}
	return nil
}

type DeviceSyncedTypes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Registration  []byte                 `protobuf:"bytes,1,opt,name=registration,proto3" json:"registration,omitempty"`
	DataType      []int32                `protobuf:"varint,2,rep,packed,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceSyncedTypes) Reset() {
	*x = DeviceSyncedTypes{}
	mi := &file_extra_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceSyncedTypes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceSyncedTypes) ProtoMessage() {}

func (x *DeviceSyncedTypes) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceSyncedTypes.ProtoReflect.Descriptor instead.
func (*DeviceSyncedTypes) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceSyncedTypes) GetRegistration() []byte {
	if x != nil {
		return x.Registration
	}
	return nil
}

func (x *DeviceSyncedTypes) GetDataType() []int32 {
	if x != nil {
		return x.DataType
	}
	return nil
}

type DeviceInfoSpecifics struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CacheGuid            []byte                 `protobuf:"bytes,1,opt,name=cache_guid,json=cacheGuid,proto3" json:"cache_guid,omitempty"`
	ClientName           []byte                 `protobuf:"bytes,2,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	DeviceType           int32                  `protobuf:"varint,3,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	SyncUserAgent        []byte                 `protobuf:"bytes,4,opt,name=sync_user_agent,json=syncUserAgent,proto3" json:"sync_user_agent,omitempty"`
	ChromeVersion        []byte                 `protobuf:"bytes,5,opt,name=chrome_version,json=chromeVersion,proto3" json:"chrome_version,omitempty"`
	SigninScopedDeviceId []byte                 `protobuf:"bytes,7,opt,name=signin_scoped_device_id,json=signinScopedDeviceId,proto3" json:"signin_scoped_device_id,omitempty"`
	LastUpdatedTimestamp int64                  `protobuf:"varint,8,opt,name=last_updated_timestamp,json=lastUpdatedTimestamp,proto3" json:"last_updated_timestamp,omitempty"`
	Model                []byte                 `protobuf:"bytes,11,opt,name=model,proto3" json:"model,omitempty"`
	Manufacturer         []byte                 `protobuf:"bytes,12,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	SyncedTypes          *DeviceSyncedTypes     `protobuf:"bytes,14,opt,name=synced_types,json=syncedTypes,proto3" json:"synced_types,omitempty"`
	OsType               int32                  `protobuf:"varint,19,opt,name=os_type,json=osType,proto3" json:"os_type,omitempty"`
	FormFactor           int32                  `protobuf:"varint,20,opt,name=form_factor,json=formFactor,proto3" json:"form_factor,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DeviceInfoSpecifics) Reset() {
	*x = DeviceInfoSpecifics{}
	mi := &file_extra_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfoSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfoSpecifics) ProtoMessage() {}

func (x *DeviceInfoSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfoSpecifics.ProtoReflect.Descriptor instead.
func (*DeviceInfoSpecifics) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{3}
}

func (x *DeviceInfoSpecifics) GetCacheGuid() []byte {
	if x != nil {
		return x.CacheGuid
	}
	return nil
}

func (x *DeviceInfoSpecifics) GetClientName() []byte {
	if x != nil {
		return x.ClientName
	}
	return nil
}

func (x *DeviceInfoSpecifics) GetDeviceType() int32 {
	if x != nil {
		return x.DeviceType
	}
	return 0
}

func (x *DeviceInfoSpecifics) GetSyncUserAgent() []byte {
	if x != nil {
		return x.SyncUserAgent
	}
	return nil
}

func (x *DeviceInfoSpecifics) GetChromeVersion() []byte {
	if x != nil {
		return x.ChromeVersion
	}
	return nil
}

func (x *DeviceInfoSpecifics) GetSigninScopedDeviceId() []byte {
	if x != nil {
		return x.SigninScopedDeviceId
	}
	return nil
}

func (x *DeviceInfoSpecifics) GetLastUpdatedTimestamp() int64 {
	if x != nil {
		return x.LastUpdatedTimestamp
	}
	return 0
}

func (x *DeviceInfoSpecifics) GetModel() []byte {
	if x != nil {
		return x.Model
	}
	return nil
}

func (x *DeviceInfoSpecifics) GetManufacturer() []byte {
	if x != nil {
		return x.Manufacturer
	}
	return nil
}

func (x *DeviceInfoSpecifics) GetSyncedTypes() *DeviceSyncedTypes {
	if x != nil {
		return x.SyncedTypes
	}
	return nil
}

func (x *DeviceInfoSpecifics) GetOsType() int32 {
	if x != nil {
		return x.OsType
	}
	return 0
}

func (x *DeviceInfoSpecifics) GetFormFactor() int32 {
	if x != nil {
		return x.FormFactor
	}
	return 0
}

type SyncDeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceInfo    *DeviceInfoSpecifics   `protobuf:"bytes,154522,opt,name=device_info,json=deviceInfo,proto3" json:"device_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncDeviceInfo) Reset() {
	*x = SyncDeviceInfo{}
	mi := &file_extra_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncDeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncDeviceInfo) ProtoMessage() {}

func (x *SyncDeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncDeviceInfo.ProtoReflect.Descriptor instead.
func (*SyncDeviceInfo) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{4}
}

func (x *SyncDeviceInfo) GetDeviceInfo() *DeviceInfoSpecifics {
	if x != nil {
		return x.DeviceInfo
	}
	return nil
}

type WebAppSpecifics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StartUrl        []byte                 `protobuf:"bytes,1,opt,name=start_url,json=startUrl,proto3" json:"start_url,omitempty"`
	Name            []byte                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UserDisplayMode int32                  `protobuf:"varint,3,opt,name=user_display_mode,json=userDisplayMode,proto3" json:"user_display_mode,omitempty"`
	ThemeColor      uint32                 `protobuf:"varint,4,opt,name=theme_color,json=themeColor,proto3" json:"theme_color,omitempty"`
	Scope           []byte                 `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	ManifestId      []byte                 `protobuf:"bytes,9,opt,name=manifest_id,json=manifestId,proto3" json:"manifest_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WebAppSpecifics) Reset() {
	*x = WebAppSpecifics{}
	mi := &file_extra_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAppSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAppSpecifics) ProtoMessage() {}

func (x *WebAppSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAppSpecifics.ProtoReflect.Descriptor instead.
func (*WebAppSpecifics) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{5}
}

func (x *WebAppSpecifics) GetStartUrl() []byte {
	if x != nil {
		return x.StartUrl
	}
	return nil
}

func (x *WebAppSpecifics) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *WebAppSpecifics) GetUserDisplayMode() int32 {
	if x != nil {
		return x.UserDisplayMode
	}
	return 0
}

func (x *WebAppSpecifics) GetThemeColor() uint32 {
	if x != nil {
		return x.ThemeColor
	}
	return 0
}

func (x *WebAppSpecifics) GetScope() []byte {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *WebAppSpecifics) GetManifestId() []byte {
	if x != nil {
		return x.ManifestId
	}
	return nil
}

type SyncWebApp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WebApp        *WebAppSpecifics       `protobuf:"bytes,673225,opt,name=web_app,json=webApp,proto3" json:"web_app,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncWebApp) Reset() {
	*x = SyncWebApp{}
	mi := &file_extra_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncWebApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncWebApp) ProtoMessage() {}

func (x *SyncWebApp) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncWebApp.ProtoReflect.Descriptor instead.
func (*SyncWebApp) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{6}
}

func (x *SyncWebApp) GetWebApp() *WebAppSpecifics {
	if x != nil {
		return x.WebApp
	}
	return nil
}

type WebauthnCredentialSpecifics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SyncId          []byte                 `protobuf:"bytes,1,opt,name=sync_id,json=syncId,proto3" json:"sync_id,omitempty"`
	CredentialId    []byte                 `protobuf:"bytes,2,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	RpId            []byte                 `protobuf:"bytes,3,opt,name=rp_id,json=rpId,proto3" json:"rp_id,omitempty"`
	UserId          []byte                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreationTime    int64                  `protobuf:"varint,6,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	UserName        []byte                 `protobuf:"bytes,7,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	UserDisplayName []byte                 `protobuf:"bytes,8,opt,name=user_display_name,json=userDisplayName,proto3" json:"user_display_name,omitempty"`
	KeyVersion      int32                  `protobuf:"varint,9,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	PrivateKey      []byte                 `protobuf:"bytes,10,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	Encrypted       []byte                 `protobuf:"bytes,12,opt,name=encrypted,proto3" json:"encrypted,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WebauthnCredentialSpecifics) Reset() {
	*x = WebauthnCredentialSpecifics{}
	mi := &file_extra_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebauthnCredentialSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebauthnCredentialSpecifics) ProtoMessage() {}

func (x *WebauthnCredentialSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebauthnCredentialSpecifics.ProtoReflect.Descriptor instead.
func (*WebauthnCredentialSpecifics) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{7}
}

func (x *WebauthnCredentialSpecifics) GetSyncId() []byte {
	if x != nil {
		return x.SyncId
	}
	return nil
}

func (x *WebauthnCredentialSpecifics) GetCredentialId() []byte {
	if x != nil {
		return x.CredentialId
	}
	return nil
}

func (x *WebauthnCredentialSpecifics) GetRpId() []byte {
	if x != nil {
		return x.RpId
	}
	return nil
}

func (x *WebauthnCredentialSpecifics) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *WebauthnCredentialSpecifics) GetCreationTime() int64 {
	if x != nil {
		return x.CreationTime
	}
	return 0
}

func (x *WebauthnCredentialSpecifics) GetUserName() []byte {
	if x != nil {
		return x.UserName
	}
	return nil
}

func (x *WebauthnCredentialSpecifics) GetUserDisplayName() []byte {
	if x != nil {
		return x.UserDisplayName
	}
	return nil
}

func (x *WebauthnCredentialSpecifics) GetKeyVersion() int32 {
	if x != nil {
		return x.KeyVersion
	}
	return 0
}

func (x *WebauthnCredentialSpecifics) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *WebauthnCredentialSpecifics) GetEncrypted() []byte {
	if x != nil {
		return x.Encrypted
	}
	return nil
}

type SyncWebauthnCredential struct {
	state              protoimpl.MessageState       `protogen:"open.v1"`
	WebauthnCredential *WebauthnCredentialSpecifics `protobuf:"bytes,895275,opt,name=webauthn_credential,json=webauthnCredential,proto3" json:"webauthn_credential,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SyncWebauthnCredential) Reset() {
	*x = SyncWebauthnCredential{}
	mi := &file_extra_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncWebauthnCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncWebauthnCredential) ProtoMessage() {}

func (x *SyncWebauthnCredential) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncWebauthnCredential.ProtoReflect.Descriptor instead.
func (*SyncWebauthnCredential) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{8}
}

func (x *SyncWebauthnCredential) GetWebauthnCredential() *WebauthnCredentialSpecifics {
	if x != nil {
		return x.WebauthnCredential
	}
	return nil
}

type AutofillSpecifics struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           []byte                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value          []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	UsageTimestamp []int64                `protobuf:"varint,3,rep,packed,name=usage_timestamp,json=usageTimestamp,proto3" json:"usage_timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AutofillSpecifics) Reset() {
	*x = AutofillSpecifics{}
	mi := &file_extra_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutofillSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutofillSpecifics) ProtoMessage() {}

func (x *AutofillSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutofillSpecifics.ProtoReflect.Descriptor instead.
func (*AutofillSpecifics) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{9}
}

func (x *AutofillSpecifics) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *AutofillSpecifics) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AutofillSpecifics) GetUsageTimestamp() []int64 {
	if x != nil {
		return x.UsageTimestamp
	}
	return nil
}

type SyncAutofill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Autofill      *AutofillSpecifics     `protobuf:"bytes,31729,opt,name=autofill,proto3" json:"autofill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAutofill) Reset() {
	*x = SyncAutofill{}
	mi := &file_extra_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAutofill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAutofill) ProtoMessage() {}

func (x *SyncAutofill) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAutofill.ProtoReflect.Descriptor instead.
func (*SyncAutofill) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{10}
}

func (x *SyncAutofill) GetAutofill() *AutofillSpecifics {
	if x != nil {
		return x.Autofill
	}
	return nil
}

type AutofillProfileSpecifics struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Guid                     []byte                 `protobuf:"bytes,15,opt,name=guid,proto3" json:"guid,omitempty"`
	Origin                   []byte                 `protobuf:"bytes,16,opt,name=origin,proto3" json:"origin,omitempty"`
	NameFirst                [][]byte               `protobuf:"bytes,2,rep,name=name_first,json=nameFirst,proto3" json:"name_first,omitempty"`
	NameMiddle               [][]byte               `protobuf:"bytes,3,rep,name=name_middle,json=nameMiddle,proto3" json:"name_middle,omitempty"`
	NameLast                 [][]byte               `protobuf:"bytes,4,rep,name=name_last,json=nameLast,proto3" json:"name_last,omitempty"`
	NameFull                 [][]byte               `protobuf:"bytes,21,rep,name=name_full,json=nameFull,proto3" json:"name_full,omitempty"`
	EmailAddress             [][]byte               `protobuf:"bytes,5,rep,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	CompanyName              []byte                 `protobuf:"bytes,6,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	AddressHomeLine1         []byte                 `protobuf:"bytes,7,opt,name=address_home_line1,json=addressHomeLine1,proto3" json:"address_home_line1,omitempty"`
	AddressHomeLine2         []byte                 `protobuf:"bytes,8,opt,name=address_home_line2,json=addressHomeLine2,proto3" json:"address_home_line2,omitempty"`
	AddressHomeCity          []byte                 `protobuf:"bytes,9,opt,name=address_home_city,json=addressHomeCity,proto3" json:"address_home_city,omitempty"`
	AddressHomeState         []byte                 `protobuf:"bytes,10,opt,name=address_home_state,json=addressHomeState,proto3" json:"address_home_state,omitempty"`
	AddressHomeZip           []byte                 `protobuf:"bytes,11,opt,name=address_home_zip,json=addressHomeZip,proto3" json:"address_home_zip,omitempty"`
	AddressHomeCountry       []byte                 `protobuf:"bytes,12,opt,name=address_home_country,json=addressHomeCountry,proto3" json:"address_home_country,omitempty"`
	PhoneHomeWholeNumber     [][]byte               `protobuf:"bytes,13,rep,name=phone_home_whole_number,json=phoneHomeWholeNumber,proto3" json:"phone_home_whole_number,omitempty"`
	AddressHomeStreetAddress []byte                 `protobuf:"bytes,27,opt,name=address_home_street_address,json=addressHomeStreetAddress,proto3" json:"address_home_street_address,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AutofillProfileSpecifics) Reset() {
	*x = AutofillProfileSpecifics{}
	mi := &file_extra_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutofillProfileSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutofillProfileSpecifics) ProtoMessage() {}

func (x *AutofillProfileSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutofillProfileSpecifics.ProtoReflect.Descriptor instead.
func (*AutofillProfileSpecifics) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{11}
}

func (x *AutofillProfileSpecifics) GetGuid() []byte {
	if x != nil {
		return x.Guid
	}
	return nil
}

func (x *AutofillProfileSpecifics) GetOrigin() []byte {
	if x != nil {
		return x.Origin
	}
	return nil
}

func (x *AutofillProfileSpecifics) GetNameFirst() [][]byte {
	if x != nil {
		return x.NameFirst
	}
	return nil
}

func (x *AutofillProfileSpecifics) GetNameMiddle() [][]byte {
	if x != nil {
		return x.NameMiddle
	}
	return nil
}

func (x *AutofillProfileSpecifics) GetNameLast() [][]byte {
	if x != nil {
		return x.NameLast
	}
	return nil
}

func (x *AutofillProfileSpecifics) GetNameFull() [][]byte {
	if x != nil {
		return x.NameFull
	}
	return nil
}

func (x *AutofillProfileSpecifics) GetEmailAddress() [][]byte {
	if x != nil {
		return x.EmailAddress
	}
	return nil
}

func (x *AutofillProfileSpecifics) GetCompanyName() []byte {
	if x != nil {
		return x.CompanyName
	}
	return nil
}

func (x *AutofillProfileSpecifics) GetAddressHomeLine1() []byte {
	if x != nil {
		return x.AddressHomeLine1
	}
	return nil
}

func (x *AutofillProfileSpecifics) GetAddressHomeLine2() []byte {
	if x != nil {
		return x.AddressHomeLine2
	}
	return nil
}

func (x *AutofillProfileSpecifics) GetAddressHomeCity() []byte {
	if x != nil {
		return x.AddressHomeCity
	}
	return nil
}

func (x *AutofillProfileSpecifics) GetAddressHomeState() []byte {
	if x != nil {
		return x.AddressHomeState
	}
	return nil
}

func (x *AutofillProfileSpecifics) GetAddressHomeZip() []byte {
	if x != nil {
		return x.AddressHomeZip
	}
	return nil
}

func (x *AutofillProfileSpecifics) GetAddressHomeCountry() []byte {
	if x != nil {
		return x.AddressHomeCountry
	}
	return nil
}

func (x *AutofillProfileSpecifics) GetPhoneHomeWholeNumber() [][]byte {
	if x != nil {
		return x.PhoneHomeWholeNumber
	}
	return nil
}

func (x *AutofillProfileSpecifics) GetAddressHomeStreetAddress() []byte {
	if x != nil {
		return x.AddressHomeStreetAddress
	}
	return nil
}

type SyncAutofillProfile struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	AutofillProfile *AutofillProfileSpecifics `protobuf:"bytes,63951,opt,name=autofill_profile,json=autofillProfile,proto3" json:"autofill_profile,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncAutofillProfile) Reset() {
	*x = SyncAutofillProfile{}
	mi := &file_extra_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAutofillProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAutofillProfile) ProtoMessage() {}

func (x *SyncAutofillProfile) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAutofillProfile.ProtoReflect.Descriptor instead.
func (*SyncAutofillProfile) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{12}
}

func (x *SyncAutofillProfile) GetAutofillProfile() *AutofillProfileSpecifics {
	if x != nil {
		return x.AutofillProfile
	}
	return nil
}

type SavedTabGroupData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         []byte                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Color         int32                  `protobuf:"varint,2,opt,name=color,proto3" json:"color,omitempty"`
	Position      int32                  `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavedTabGroupData) Reset() {
	*x = SavedTabGroupData{}
	mi := &file_extra_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavedTabGroupData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavedTabGroupData) ProtoMessage() {}

func (x *SavedTabGroupData) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavedTabGroupData.ProtoReflect.Descriptor instead.
func (*SavedTabGroupData) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{13}
}

func (x *SavedTabGroupData) GetTitle() []byte {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *SavedTabGroupData) GetColor() int32 {
	if x != nil {
		return x.Color
	}
	return 0
}

func (x *SavedTabGroupData) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type SavedTabGroupTab struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupGuid     []byte                 `protobuf:"bytes,1,opt,name=group_guid,json=groupGuid,proto3" json:"group_guid,omitempty"`
	Url           []byte                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title         []byte                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Position      int32                  `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SavedTabGroupTab) Reset() {
	*x = SavedTabGroupTab{}
	mi := &file_extra_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavedTabGroupTab) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavedTabGroupTab) ProtoMessage() {}

func (x *SavedTabGroupTab) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavedTabGroupTab.ProtoReflect.Descriptor instead.
func (*SavedTabGroupTab) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{14}
}

func (x *SavedTabGroupTab) GetGroupGuid() []byte {
	if x != nil {
		return x.GroupGuid
	}
	return nil
}

func (x *SavedTabGroupTab) GetUrl() []byte {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *SavedTabGroupTab) GetTitle() []byte {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *SavedTabGroupTab) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type SavedTabGroupSpecifics struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	Guid                           []byte                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	CreationTimeWindowsEpochMicros int64                  `protobuf:"varint,2,opt,name=creation_time_windows_epoch_micros,json=creationTimeWindowsEpochMicros,proto3" json:"creation_time_windows_epoch_micros,omitempty"`
	UpdateTimeWindowsEpochMicros   int64                  `protobuf:"varint,3,opt,name=update_time_windows_epoch_micros,json=updateTimeWindowsEpochMicros,proto3" json:"update_time_windows_epoch_micros,omitempty"`
	Group                          *SavedTabGroupData     `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	Tab                            *SavedTabGroupTab      `protobuf:"bytes,5,opt,name=tab,proto3" json:"tab,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *SavedTabGroupSpecifics) Reset() {
	*x = SavedTabGroupSpecifics{}
	mi := &file_extra_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SavedTabGroupSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SavedTabGroupSpecifics) ProtoMessage() {}

func (x *SavedTabGroupSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SavedTabGroupSpecifics.ProtoReflect.Descriptor instead.
func (*SavedTabGroupSpecifics) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{15}
}

func (x *SavedTabGroupSpecifics) GetGuid() []byte {
	if x != nil {
		return x.Guid
	}
	return nil
}

func (x *SavedTabGroupSpecifics) GetCreationTimeWindowsEpochMicros() int64 {
	if x != nil {
		return x.CreationTimeWindowsEpochMicros
	}
	return 0
}

func (x *SavedTabGroupSpecifics) GetUpdateTimeWindowsEpochMicros() int64 {
	if x != nil {
		return x.UpdateTimeWindowsEpochMicros
	}
	return 0
}

func (x *SavedTabGroupSpecifics) GetGroup() *SavedTabGroupData {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *SavedTabGroupSpecifics) GetTab() *SavedTabGroupTab {
	if x != nil {
		return x.Tab
	}
	return nil
}

type SyncSavedTabGroup struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	SavedTabGroup *SavedTabGroupSpecifics `protobuf:"bytes,1004874,opt,name=saved_tab_group,json=savedTabGroup,proto3" json:"saved_tab_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSavedTabGroup) Reset() {
	*x = SyncSavedTabGroup{}
	mi := &file_extra_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSavedTabGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSavedTabGroup) ProtoMessage() {}

func (x *SyncSavedTabGroup) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSavedTabGroup.ProtoReflect.Descriptor instead.
func (*SyncSavedTabGroup) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{16}
}

func (x *SyncSavedTabGroup) GetSavedTabGroup() *SavedTabGroupSpecifics {
	if x != nil {
		return x.SavedTabGroup
	}
	return nil
}

type SessionTabNavigation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VirtualUrl     []byte                 `protobuf:"bytes,2,opt,name=virtual_url,json=virtualUrl,proto3" json:"virtual_url,omitempty"`
	Referrer       []byte                 `protobuf:"bytes,3,opt,name=referrer,proto3" json:"referrer,omitempty"`
	Title          []byte                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	UniqueId       int32                  `protobuf:"varint,8,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
	TimestampMsec  int64                  `protobuf:"varint,9,opt,name=timestamp_msec,json=timestampMsec,proto3" json:"timestamp_msec,omitempty"`
	FaviconUrl     []byte                 `protobuf:"bytes,17,opt,name=favicon_url,json=faviconUrl,proto3" json:"favicon_url,omitempty"`
	HttpStatusCode int32                  `protobuf:"varint,20,opt,name=http_status_code,json=httpStatusCode,proto3" json:"http_status_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SessionTabNavigation) Reset() {
	*x = SessionTabNavigation{}
	mi := &file_extra_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionTabNavigation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionTabNavigation) ProtoMessage() {}

func (x *SessionTabNavigation) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionTabNavigation.ProtoReflect.Descriptor instead.
func (*SessionTabNavigation) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{17}
}

func (x *SessionTabNavigation) GetVirtualUrl() []byte {
	if x != nil {
		return x.VirtualUrl
	}
	return nil
}

func (x *SessionTabNavigation) GetReferrer() []byte {
	if x != nil {
		return x.Referrer
	}
	return nil
}

func (x *SessionTabNavigation) GetTitle() []byte {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *SessionTabNavigation) GetUniqueId() int32 {
	if x != nil {
		return x.UniqueId
	}
	return 0
}

func (x *SessionTabNavigation) GetTimestampMsec() int64 {
	if x != nil {
		return x.TimestampMsec
	}
	return 0
}

func (x *SessionTabNavigation) GetFaviconUrl() []byte {
	if x != nil {
		return x.FaviconUrl
	}
	return nil
}

func (x *SessionTabNavigation) GetHttpStatusCode() int32 {
	if x != nil {
		return x.HttpStatusCode
	}
	return 0
}

type SessionTabData struct {
	state                  protoimpl.MessageState  `protogen:"open.v1"`
	WindowId               int32                   `protobuf:"varint,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	TabId                  int32                   `protobuf:"varint,2,opt,name=tab_id,json=tabId,proto3" json:"tab_id,omitempty"`
	TabVisualIndex         int32                   `protobuf:"varint,3,opt,name=tab_visual_index,json=tabVisualIndex,proto3" json:"tab_visual_index,omitempty"`
	CurrentNavigationIndex int32                   `protobuf:"varint,4,opt,name=current_navigation_index,json=currentNavigationIndex,proto3" json:"current_navigation_index,omitempty"`
	Pinned                 bool                    `protobuf:"varint,5,opt,name=pinned,proto3" json:"pinned,omitempty"`
	ExtensionAppId         []byte                  `protobuf:"bytes,6,opt,name=extension_app_id,json=extensionAppId,proto3" json:"extension_app_id,omitempty"`
	Navigation             []*SessionTabNavigation `protobuf:"bytes,7,rep,name=navigation,proto3" json:"navigation,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SessionTabData) Reset() {
	*x = SessionTabData{}
	mi := &file_extra_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionTabData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionTabData) ProtoMessage() {}

func (x *SessionTabData) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionTabData.ProtoReflect.Descriptor instead.
func (*SessionTabData) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{18}
}

func (x *SessionTabData) GetWindowId() int32 {
	if x != nil {
		return x.WindowId
	}
	return 0
}

func (x *SessionTabData) GetTabId() int32 {
	if x != nil {
		return x.TabId
	}
	return 0
}

func (x *SessionTabData) GetTabVisualIndex() int32 {
	if x != nil {
		return x.TabVisualIndex
	}
	return 0
}

func (x *SessionTabData) GetCurrentNavigationIndex() int32 {
	if x != nil {
		return x.CurrentNavigationIndex
	}
	return 0
}

func (x *SessionTabData) GetPinned() bool {
	if x != nil {
		return x.Pinned
	}
	return false
}

func (x *SessionTabData) GetExtensionAppId() []byte {
	if x != nil {
		return x.ExtensionAppId
	}
	return nil
}

func (x *SessionTabData) GetNavigation() []*SessionTabNavigation {
	if x != nil {
		return x.Navigation
	}
	return nil
}

type SessionWindowData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	WindowId         int32                  `protobuf:"varint,1,opt,name=window_id,json=windowId,proto3" json:"window_id,omitempty"`
	SelectedTabIndex int32                  `protobuf:"varint,2,opt,name=selected_tab_index,json=selectedTabIndex,proto3" json:"selected_tab_index,omitempty"`
	Tab              []int32                `protobuf:"varint,4,rep,packed,name=tab,proto3" json:"tab,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionWindowData) Reset() {
	*x = SessionWindowData{}
	mi := &file_extra_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionWindowData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionWindowData) ProtoMessage() {}

func (x *SessionWindowData) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionWindowData.ProtoReflect.Descriptor instead.
func (*SessionWindowData) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{19}
}

func (x *SessionWindowData) GetWindowId() int32 {
	if x != nil {
		return x.WindowId
	}
	return 0
}

func (x *SessionWindowData) GetSelectedTabIndex() int32 {
	if x != nil {
		return x.SelectedTabIndex
	}
	return 0
}

func (x *SessionWindowData) GetTab() []int32 {
	if x != nil {
		return x.Tab
	}
	return nil
}

type SessionHeaderData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Window        []*SessionWindowData   `protobuf:"bytes,2,rep,name=window,proto3" json:"window,omitempty"`
	ClientName    []byte                 `protobuf:"bytes,3,opt,name=client_name,json=clientName,proto3" json:"client_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionHeaderData) Reset() {
	*x = SessionHeaderData{}
	mi := &file_extra_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionHeaderData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionHeaderData) ProtoMessage() {}

func (x *SessionHeaderData) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionHeaderData.ProtoReflect.Descriptor instead.
func (*SessionHeaderData) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{20}
}

func (x *SessionHeaderData) GetWindow() []*SessionWindowData {
	if x != nil {
		return x.Window
	}
	return nil
}

func (x *SessionHeaderData) GetClientName() []byte {
	if x != nil {
		return x.ClientName
	}
	return nil
}

type SessionSpecificsMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionTag    []byte                 `protobuf:"bytes,1,opt,name=session_tag,json=sessionTag,proto3" json:"session_tag,omitempty"`
	Header        *SessionHeaderData     `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Tab           *SessionTabData        `protobuf:"bytes,3,opt,name=tab,proto3" json:"tab,omitempty"`
	TabNodeId     int32                  `protobuf:"varint,4,opt,name=tab_node_id,json=tabNodeId,proto3" json:"tab_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionSpecificsMsg) Reset() {
	*x = SessionSpecificsMsg{}
	mi := &file_extra_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionSpecificsMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionSpecificsMsg) ProtoMessage() {}

func (x *SessionSpecificsMsg) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionSpecificsMsg.ProtoReflect.Descriptor instead.
func (*SessionSpecificsMsg) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{21}
}

func (x *SessionSpecificsMsg) GetSessionTag() []byte {
	if x != nil {
		return x.SessionTag
	}
	return nil
}

func (x *SessionSpecificsMsg) GetHeader() *SessionHeaderData {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SessionSpecificsMsg) GetTab() *SessionTabData {
	if x != nil {
		return x.Tab
	}
	return nil
}

func (x *SessionSpecificsMsg) GetTabNodeId() int32 {
	if x != nil {
		return x.TabNodeId
	}
	return 0
}

type SyncSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *SessionSpecificsMsg   `protobuf:"bytes,50119,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSession) Reset() {
	*x = SyncSession{}
	mi := &file_extra_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSession) ProtoMessage() {}

func (x *SyncSession) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSession.ProtoReflect.Descriptor instead.
func (*SyncSession) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{22}
}

func (x *SyncSession) GetSession() *SessionSpecificsMsg {
	if x != nil {
		return x.Session
	}
	return nil
}

type UserConsentSpecifics struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	AccountId             []byte                 `protobuf:"bytes,6,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	ClientConsentTimeUsec int64                  `protobuf:"varint,12,opt,name=client_consent_time_usec,json=clientConsentTimeUsec,proto3" json:"client_consent_time_usec,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *UserConsentSpecifics) Reset() {
	*x = UserConsentSpecifics{}
	mi := &file_extra_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserConsentSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserConsentSpecifics) ProtoMessage() {}

func (x *UserConsentSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserConsentSpecifics.ProtoReflect.Descriptor instead.
func (*UserConsentSpecifics) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{23}
}

func (x *UserConsentSpecifics) GetAccountId() []byte {
	if x != nil {
		return x.AccountId
	}
	return nil
}

func (x *UserConsentSpecifics) GetClientConsentTimeUsec() int64 {
	if x != nil {
		return x.ClientConsentTimeUsec
	}
	return 0
}

type SyncUserConsent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserConsent   *UserConsentSpecifics  `protobuf:"bytes,556014,opt,name=user_consent,json=userConsent,proto3" json:"user_consent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncUserConsent) Reset() {
	*x = SyncUserConsent{}
	mi := &file_extra_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUserConsent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUserConsent) ProtoMessage() {}

func (x *SyncUserConsent) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUserConsent.ProtoReflect.Descriptor instead.
func (*SyncUserConsent) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{24}
}

func (x *SyncUserConsent) GetUserConsent() *UserConsentSpecifics {
	if x != nil {
		return x.UserConsent
	}
	return nil
}

type GlobalIdDirective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GlobalId      []int64                `protobuf:"varint,1,rep,packed,name=global_id,json=globalId,proto3" json:"global_id,omitempty"`
	StartTimeUsec int64                  `protobuf:"varint,2,opt,name=start_time_usec,json=startTimeUsec,proto3" json:"start_time_usec,omitempty"`
	EndTimeUsec   int64                  `protobuf:"varint,3,opt,name=end_time_usec,json=endTimeUsec,proto3" json:"end_time_usec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalIdDirective) Reset() {
	*x = GlobalIdDirective{}
	mi := &file_extra_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalIdDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalIdDirective) ProtoMessage() {}

func (x *GlobalIdDirective) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalIdDirective.ProtoReflect.Descriptor instead.
func (*GlobalIdDirective) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{25}
}

func (x *GlobalIdDirective) GetGlobalId() []int64 {
	if x != nil {
		return x.GlobalId
	}
	return nil
}

func (x *GlobalIdDirective) GetStartTimeUsec() int64 {
	if x != nil {
		return x.StartTimeUsec
	}
	return 0
}

func (x *GlobalIdDirective) GetEndTimeUsec() int64 {
	if x != nil {
		return x.EndTimeUsec
	}
	return 0
}

type TimeRangeDirective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartTimeUsec int64                  `protobuf:"varint,1,opt,name=start_time_usec,json=startTimeUsec,proto3" json:"start_time_usec,omitempty"`
	EndTimeUsec   int64                  `protobuf:"varint,2,opt,name=end_time_usec,json=endTimeUsec,proto3" json:"end_time_usec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRangeDirective) Reset() {
	*x = TimeRangeDirective{}
	mi := &file_extra_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRangeDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRangeDirective) ProtoMessage() {}

func (x *TimeRangeDirective) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRangeDirective.ProtoReflect.Descriptor instead.
func (*TimeRangeDirective) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{26}
}

func (x *TimeRangeDirective) GetStartTimeUsec() int64 {
	if x != nil {
		return x.StartTimeUsec
	}
	return 0
}

func (x *TimeRangeDirective) GetEndTimeUsec() int64 {
	if x != nil {
		return x.EndTimeUsec
	}
	return 0
}

type UrlDirective struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           []byte                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	EndTimeUsec   int64                  `protobuf:"varint,2,opt,name=end_time_usec,json=endTimeUsec,proto3" json:"end_time_usec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlDirective) Reset() {
	*x = UrlDirective{}
	mi := &file_extra_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlDirective) ProtoMessage() {}

func (x *UrlDirective) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlDirective.ProtoReflect.Descriptor instead.
func (*UrlDirective) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{27}
}

func (x *UrlDirective) GetUrl() []byte {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *UrlDirective) GetEndTimeUsec() int64 {
	if x != nil {
		return x.EndTimeUsec
	}
	return 0
}

type HistoryDeleteDirectiveSpecifics struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	GlobalIdDirective  *GlobalIdDirective     `protobuf:"bytes,1,opt,name=global_id_directive,json=globalIdDirective,proto3" json:"global_id_directive,omitempty"`
	TimeRangeDirective *TimeRangeDirective    `protobuf:"bytes,2,opt,name=time_range_directive,json=timeRangeDirective,proto3" json:"time_range_directive,omitempty"`
	UrlDirective       *UrlDirective          `protobuf:"bytes,3,opt,name=url_directive,json=urlDirective,proto3" json:"url_directive,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HistoryDeleteDirectiveSpecifics) Reset() {
	*x = HistoryDeleteDirectiveSpecifics{}
	mi := &file_extra_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryDeleteDirectiveSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryDeleteDirectiveSpecifics) ProtoMessage() {}

func (x *HistoryDeleteDirectiveSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryDeleteDirectiveSpecifics.ProtoReflect.Descriptor instead.
func (*HistoryDeleteDirectiveSpecifics) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{28}
}

func (x *HistoryDeleteDirectiveSpecifics) GetGlobalIdDirective() *GlobalIdDirective {
	if x != nil {
		return x.GlobalIdDirective
	}
	return nil
}

func (x *HistoryDeleteDirectiveSpecifics) GetTimeRangeDirective() *TimeRangeDirective {
	if x != nil {
		return x.TimeRangeDirective
	}
	return nil
}

func (x *HistoryDeleteDirectiveSpecifics) GetUrlDirective() *UrlDirective {
	if x != nil {
		return x.UrlDirective
	}
	return nil
}

type SyncHistoryDeleteDirective struct {
	state                  protoimpl.MessageState           `protogen:"open.v1"`
	HistoryDeleteDirective *HistoryDeleteDirectiveSpecifics `protobuf:"bytes,150251,opt,name=history_delete_directive,json=historyDeleteDirective,proto3" json:"history_delete_directive,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SyncHistoryDeleteDirective) Reset() {
	*x = SyncHistoryDeleteDirective{}
	mi := &file_extra_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncHistoryDeleteDirective) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncHistoryDeleteDirective) ProtoMessage() {}

func (x *SyncHistoryDeleteDirective) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncHistoryDeleteDirective.ProtoReflect.Descriptor instead.
func (*SyncHistoryDeleteDirective) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{29}
}

func (x *SyncHistoryDeleteDirective) GetHistoryDeleteDirective() *HistoryDeleteDirectiveSpecifics {
	if x != nil {
		return x.HistoryDeleteDirective
	}
	return nil
}

type NigoriEncryptedData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyName       []byte                 `protobuf:"bytes,1,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	CipherText    []byte                 `protobuf:"bytes,2,opt,name=cipher_text,json=cipherText,proto3" json:"cipher_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NigoriEncryptedData) Reset() {
	*x = NigoriEncryptedData{}
	mi := &file_extra_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NigoriEncryptedData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NigoriEncryptedData) ProtoMessage() {}

func (x *NigoriEncryptedData) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NigoriEncryptedData.ProtoReflect.Descriptor instead.
func (*NigoriEncryptedData) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{30}
}

func (x *NigoriEncryptedData) GetKeyName() []byte {
	if x != nil {
		return x.KeyName
	}
	return nil
}

func (x *NigoriEncryptedData) GetCipherText() []byte {
	if x != nil {
		return x.CipherText
	}
	return nil
}

type NigoriSpecifics struct {
	state                               protoimpl.MessageState `protogen:"open.v1"`
	EncryptionKeybag                    *NigoriEncryptedData   `protobuf:"bytes,1,opt,name=encryption_keybag,json=encryptionKeybag,proto3" json:"encryption_keybag,omitempty"`
	KeybagIsFrozen                      bool                   `protobuf:"varint,2,opt,name=keybag_is_frozen,json=keybagIsFrozen,proto3" json:"keybag_is_frozen,omitempty"`
	EncryptEverything                   bool                   `protobuf:"varint,12,opt,name=encrypt_everything,json=encryptEverything,proto3" json:"encrypt_everything,omitempty"`
	PassphraseType                      int32                  `protobuf:"varint,13,opt,name=passphrase_type,json=passphraseType,proto3" json:"passphrase_type,omitempty"`
	KeystoreMigrationTime               int64                  `protobuf:"varint,14,opt,name=keystore_migration_time,json=keystoreMigrationTime,proto3" json:"keystore_migration_time,omitempty"`
	CustomPassphraseTime                int64                  `protobuf:"varint,16,opt,name=custom_passphrase_time,json=customPassphraseTime,proto3" json:"custom_passphrase_time,omitempty"`
	CustomPassphraseKeyDerivationMethod int32                  `protobuf:"varint,17,opt,name=custom_passphrase_key_derivation_method,json=customPassphraseKeyDerivationMethod,proto3" json:"custom_passphrase_key_derivation_method,omitempty"`
	CustomPassphraseKeyDerivationSalt   []byte                 `protobuf:"bytes,18,opt,name=custom_passphrase_key_derivation_salt,json=customPassphraseKeyDerivationSalt,proto3" json:"custom_passphrase_key_derivation_salt,omitempty"`
	CrossUserSharingPublicKey           []byte                 `protobuf:"bytes,24,opt,name=cross_user_sharing_public_key,json=crossUserSharingPublicKey,proto3" json:"cross_user_sharing_public_key,omitempty"`
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *NigoriSpecifics) Reset() {
	*x = NigoriSpecifics{}
	mi := &file_extra_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NigoriSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NigoriSpecifics) ProtoMessage() {}

func (x *NigoriSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NigoriSpecifics.ProtoReflect.Descriptor instead.
func (*NigoriSpecifics) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{31}
}

func (x *NigoriSpecifics) GetEncryptionKeybag() *NigoriEncryptedData {
	if x != nil {
		return x.EncryptionKeybag
	}
	return nil
}

func (x *NigoriSpecifics) GetKeybagIsFrozen() bool {
	if x != nil {
		return x.KeybagIsFrozen
	}
	return false
}

func (x *NigoriSpecifics) GetEncryptEverything() bool {
	if x != nil {
		return x.EncryptEverything
	}
	return false
}

func (x *NigoriSpecifics) GetPassphraseType() int32 {
	if x != nil {
		return x.PassphraseType
	}
	return 0
}

func (x *NigoriSpecifics) GetKeystoreMigrationTime() int64 {
	if x != nil {
		return x.KeystoreMigrationTime
	}
	return 0
}

func (x *NigoriSpecifics) GetCustomPassphraseTime() int64 {
	if x != nil {
		return x.CustomPassphraseTime
	}
	return 0
}

func (x *NigoriSpecifics) GetCustomPassphraseKeyDerivationMethod() int32 {
	if x != nil {
		return x.CustomPassphraseKeyDerivationMethod
	}
	return 0
}

func (x *NigoriSpecifics) GetCustomPassphraseKeyDerivationSalt() []byte {
	if x != nil {
		return x.CustomPassphraseKeyDerivationSalt
	}
	return nil
}

func (x *NigoriSpecifics) GetCrossUserSharingPublicKey() []byte {
	if x != nil {
		return x.CrossUserSharingPublicKey
	}
	return nil
}

type SyncNigori struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nigori        *NigoriSpecifics       `protobuf:"bytes,47745,opt,name=nigori,proto3" json:"nigori,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncNigori) Reset() {
	*x = SyncNigori{}
	mi := &file_extra_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncNigori) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncNigori) ProtoMessage() {}

func (x *SyncNigori) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncNigori.ProtoReflect.Descriptor instead.
func (*SyncNigori) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{32}
}

func (x *SyncNigori) GetNigori() *NigoriSpecifics {
	if x != nil {
		return x.Nigori
	}
	return nil
}

type EdgeEDropSpecifics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          []byte                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	Title         []byte                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ContentType   []byte                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	CreationTime  int64                  `protobuf:"varint,5,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeEDropSpecifics) Reset() {
	*x = EdgeEDropSpecifics{}
	mi := &file_extra_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeEDropSpecifics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeEDropSpecifics) ProtoMessage() {}

func (x *EdgeEDropSpecifics) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeEDropSpecifics.ProtoReflect.Descriptor instead.
func (*EdgeEDropSpecifics) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{33}
}

func (x *EdgeEDropSpecifics) GetGuid() []byte {
	if x != nil {
		return x.Guid
	}
	return nil
}

func (x *EdgeEDropSpecifics) GetTitle() []byte {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *EdgeEDropSpecifics) GetContentType() []byte {
	if x != nil {
		return x.ContentType
	}
	return nil
}

func (x *EdgeEDropSpecifics) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EdgeEDropSpecifics) GetCreationTime() int64 {
	if x != nil {
		return x.CreationTime
	}
	return 0
}

type SyncEdgeEDrop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EdgeEDrop     *EdgeEDropSpecifics    `protobuf:"bytes,956368,opt,name=edge_e_drop,json=edgeEDrop,proto3" json:"edge_e_drop,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncEdgeEDrop) Reset() {
	*x = SyncEdgeEDrop{}
	mi := &file_extra_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncEdgeEDrop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncEdgeEDrop) ProtoMessage() {}

func (x *SyncEdgeEDrop) ProtoReflect() protoreflect.Message {
	mi := &file_extra_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncEdgeEDrop.ProtoReflect.Descriptor instead.
func (*SyncEdgeEDrop) Descriptor() ([]byte, []int) {
	return file_extra_proto_rawDescGZIP(), []int{34}
}

func (x *SyncEdgeEDrop) GetEdgeEDrop() *EdgeEDropSpecifics {
	if x != nil {
		return x.EdgeEDrop
	}
	return nil
}

var File_extra_proto protoreflect.FileDescriptor

const file_extra_proto_rawDesc = "" +
	"\n" +
	"\vextra.proto\x12\tsyncproto\"\xc4\x03\n" +
	"\x16SendTabToSelfSpecifics\x12\x14\n" +
	"\x05title\x18\x01 \x01(\fR\x05title\x12\x10\n" +
	"\x03url\x18\x02 \x01(\fR\x03url\x12(\n" +
	"\x10shared_time_usec\x18\x03 \x01(\x03R\x0esharedTimeUsec\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\fR\n" +
	"deviceName\x12\x12\n" +
	"\x04guid\x18\x05 \x01(\fR\x04guid\x12@\n" +
	"\x1dtarget_device_sync_cache_guid\x18\a \x01(\fR\x19targetDeviceSyncCacheGuid\x125\n" +
	"\x16notification_dismissed\x18\b \x01(\bR\x15notificationDismissed\x12\x16\n" +
	"\x06opened\x18\t \x01(\bR\x06opened\x12J\n" +
	"\"received_time_windows_epoch_micros\x18\r \x01(\x03R\x1ereceivedTimeWindowsEpochMicros\x12F\n" +
	" opened_time_windows_epoch_micros\x18\x0e \x01(\x03R\x1copenedTimeWindowsEpochMicros\"a\n" +
	"\x11SyncSendTabToSelf\x12L\n" +
	"\x10send_tab_to_self\x18\xfc\xde$ \x01(\v2!.syncproto.SendTabToSelfSpecificsR\rsendTabToSelf\"T\n" +
	"\x11DeviceSyncedTypes\x12\"\n" +
	"\fregistration\x18\x01 \x01(\fR\fregistration\x12\x1b\n" +
	"\tdata_type\x18\x02 \x03(\x05R\bdataType\"\xe7\x03\n" +
	"\x13DeviceInfoSpecifics\x12\x1d\n" +
	"\n" +
	"cache_guid\x18\x01 \x01(\fR\tcacheGuid\x12\x1f\n" +
	"\vclient_name\x18\x02 \x01(\fR\n" +
	"clientName\x12\x1f\n" +
	"\vdevice_type\x18\x03 \x01(\x05R\n" +
	"deviceType\x12&\n" +
	"\x0fsync_user_agent\x18\x04 \x01(\fR\rsyncUserAgent\x12%\n" +
	"\x0echrome_version\x18\x05 \x01(\fR\rchromeVersion\x125\n" +
	"\x17signin_scoped_device_id\x18\a \x01(\fR\x14signinScopedDeviceId\x124\n" +
	"\x16last_updated_timestamp\x18\b \x01(\x03R\x14lastUpdatedTimestamp\x12\x14\n" +
	"\x05model\x18\v \x01(\fR\x05model\x12\"\n" +
	"\fmanufacturer\x18\f \x01(\fR\fmanufacturer\x12?\n" +
	"\fsynced_types\x18\x0e \x01(\v2\x1c.syncproto.DeviceSyncedTypesR\vsyncedTypes\x12\x17\n" +
	"\aos_type\x18\x13 \x01(\x05R\x06osType\x12\x1f\n" +
	"\vform_factor\x18\x14 \x01(\x05R\n" +
	"formFactor\"S\n" +
	"\x0eSyncDeviceInfo\x12A\n" +
	"\vdevice_info\x18\x9a\xb7\t \x01(\v2\x1e.syncproto.DeviceInfoSpecificsR\n" +
	"deviceInfo\"\xc6\x01\n" +
	"\x0fWebAppSpecifics\x12\x1b\n" +
	"\tstart_url\x18\x01 \x01(\fR\bstartUrl\x12\x12\n" +
	"\x04name\x18\x02 \x01(\fR\x04name\x12*\n" +
	"\x11user_display_mode\x18\x03 \x01(\x05R\x0fuserDisplayMode\x12\x1f\n" +
	"\vtheme_color\x18\x04 \x01(\rR\n" +
	"themeColor\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\fR\x05scope\x12\x1f\n" +
	"\vmanifest_id\x18\t \x01(\fR\n" +
	"manifestId\"C\n" +
	"\n" +
	"SyncWebApp\x125\n" +
	"\aweb_app\x18ɋ) \x01(\v2\x1a.syncproto.WebAppSpecificsR\x06webApp\"\xd7\x02\n" +
	"\x1bWebauthnCredentialSpecifics\x12\x17\n" +
	"\async_id\x18\x01 \x01(\fR\x06syncId\x12#\n" +
	"\rcredential_id\x18\x02 \x01(\fR\fcredentialId\x12\x13\n" +
	"\x05rp_id\x18\x03 \x01(\fR\x04rpId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\fR\x06userId\x12#\n" +
	"\rcreation_time\x18\x06 \x01(\x03R\fcreationTime\x12\x1b\n" +
	"\tuser_name\x18\a \x01(\fR\buserName\x12*\n" +
	"\x11user_display_name\x18\b \x01(\fR\x0fuserDisplayName\x12\x1f\n" +
	"\vkey_version\x18\t \x01(\x05R\n" +
	"keyVersion\x12\x1f\n" +
	"\vprivate_key\x18\n" +
	" \x01(\fR\n" +
	"privateKey\x12\x1c\n" +
	"\tencrypted\x18\f \x01(\fR\tencrypted\"s\n" +
	"\x16SyncWebauthnCredential\x12Y\n" +
	"\x13webauthn_credential\x18\xab\xd26 \x01(\v2&.syncproto.WebauthnCredentialSpecificsR\x12webauthnCredential\"f\n" +
	"\x11AutofillSpecifics\x12\x12\n" +
	"\x04name\x18\x01 \x01(\fR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12'\n" +
	"\x0fusage_timestamp\x18\x03 \x03(\x03R\x0eusageTimestamp\"J\n" +
	"\fSyncAutofill\x12:\n" +
	"\bautofill\x18\xf1\xf7\x01 \x01(\v2\x1c.syncproto.AutofillSpecificsR\bautofill\"\x90\x05\n" +
	"\x18AutofillProfileSpecifics\x12\x12\n" +
	"\x04guid\x18\x0f \x01(\fR\x04guid\x12\x16\n" +
	"\x06origin\x18\x10 \x01(\fR\x06origin\x12\x1d\n" +
	"\n" +
	"name_first\x18\x02 \x03(\fR\tnameFirst\x12\x1f\n" +
	"\vname_middle\x18\x03 \x03(\fR\n" +
	"nameMiddle\x12\x1b\n" +
	"\tname_last\x18\x04 \x03(\fR\bnameLast\x12\x1b\n" +
	"\tname_full\x18\x15 \x03(\fR\bnameFull\x12#\n" +
	"\remail_address\x18\x05 \x03(\fR\femailAddress\x12!\n" +
	"\fcompany_name\x18\x06 \x01(\fR\vcompanyName\x12,\n" +
	"\x12address_home_line1\x18\a \x01(\fR\x10addressHomeLine1\x12,\n" +
	"\x12address_home_line2\x18\b \x01(\fR\x10addressHomeLine2\x12*\n" +
	"\x11address_home_city\x18\t \x01(\fR\x0faddressHomeCity\x12,\n" +
	"\x12address_home_state\x18\n" +
	" \x01(\fR\x10addressHomeState\x12(\n" +
	"\x10address_home_zip\x18\v \x01(\fR\x0eaddressHomeZip\x120\n" +
	"\x14address_home_country\x18\f \x01(\fR\x12addressHomeCountry\x125\n" +
	"\x17phone_home_whole_number\x18\r \x03(\fR\x14phoneHomeWholeNumber\x12=\n" +
	"\x1baddress_home_street_address\x18\x1b \x01(\fR\x18addressHomeStreetAddress\"g\n" +
	"\x13SyncAutofillProfile\x12P\n" +
	"\x10autofill_profile\x18\xcf\xf3\x03 \x01(\v2#.syncproto.AutofillProfileSpecificsR\x0fautofillProfile\"[\n" +
	"\x11SavedTabGroupData\x12\x14\n" +
	"\x05title\x18\x01 \x01(\fR\x05title\x12\x14\n" +
	"\x05color\x18\x02 \x01(\x05R\x05color\x12\x1a\n" +
	"\bposition\x18\x03 \x01(\x05R\bposition\"u\n" +
	"\x10SavedTabGroupTab\x12\x1d\n" +
	"\n" +
	"group_guid\x18\x01 \x01(\fR\tgroupGuid\x12\x10\n" +
	"\x03url\x18\x02 \x01(\fR\x03url\x12\x14\n" +
	"\x05title\x18\x03 \x01(\fR\x05title\x12\x1a\n" +
	"\bposition\x18\x04 \x01(\x05R\bposition\"\xa3\x02\n" +
	"\x16SavedTabGroupSpecifics\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\fR\x04guid\x12J\n" +
	"\"creation_time_windows_epoch_micros\x18\x02 \x01(\x03R\x1ecreationTimeWindowsEpochMicros\x12F\n" +
	" update_time_windows_epoch_micros\x18\x03 \x01(\x03R\x1cupdateTimeWindowsEpochMicros\x122\n" +
	"\x05group\x18\x04 \x01(\v2\x1c.syncproto.SavedTabGroupDataR\x05group\x12-\n" +
	"\x03tab\x18\x05 \x01(\v2\x1b.syncproto.SavedTabGroupTabR\x03tab\"`\n" +
	"\x11SyncSavedTabGroup\x12K\n" +
	"\x0fsaved_tab_group\x18ʪ= \x01(\v2!.syncproto.SavedTabGroupSpecificsR\rsavedTabGroup\"\xf8\x01\n" +
	"\x14SessionTabNavigation\x12\x1f\n" +
	"\vvirtual_url\x18\x02 \x01(\fR\n" +
	"virtualUrl\x12\x1a\n" +
	"\breferrer\x18\x03 \x01(\fR\breferrer\x12\x14\n" +
	"\x05title\x18\x04 \x01(\fR\x05title\x12\x1b\n" +
	"\tunique_id\x18\b \x01(\x05R\buniqueId\x12%\n" +
	"\x0etimestamp_msec\x18\t \x01(\x03R\rtimestampMsec\x12\x1f\n" +
	"\vfavicon_url\x18\x11 \x01(\fR\n" +
	"faviconUrl\x12(\n" +
	"\x10http_status_code\x18\x14 \x01(\x05R\x0ehttpStatusCode\"\xab\x02\n" +
	"\x0eSessionTabData\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\x05R\bwindowId\x12\x15\n" +
	"\x06tab_id\x18\x02 \x01(\x05R\x05tabId\x12(\n" +
	"\x10tab_visual_index\x18\x03 \x01(\x05R\x0etabVisualIndex\x128\n" +
	"\x18current_navigation_index\x18\x04 \x01(\x05R\x16currentNavigationIndex\x12\x16\n" +
	"\x06pinned\x18\x05 \x01(\bR\x06pinned\x12(\n" +
	"\x10extension_app_id\x18\x06 \x01(\fR\x0eextensionAppId\x12?\n" +
	"\n" +
	"navigation\x18\a \x03(\v2\x1f.syncproto.SessionTabNavigationR\n" +
	"navigation\"p\n" +
	"\x11SessionWindowData\x12\x1b\n" +
	"\twindow_id\x18\x01 \x01(\x05R\bwindowId\x12,\n" +
	"\x12selected_tab_index\x18\x02 \x01(\x05R\x10selectedTabIndex\x12\x10\n" +
	"\x03tab\x18\x04 \x03(\x05R\x03tab\"j\n" +
	"\x11SessionHeaderData\x124\n" +
	"\x06window\x18\x02 \x03(\v2\x1c.syncproto.SessionWindowDataR\x06window\x12\x1f\n" +
	"\vclient_name\x18\x03 \x01(\fR\n" +
	"clientName\"\xb9\x01\n" +
	"\x13SessionSpecificsMsg\x12\x1f\n" +
	"\vsession_tag\x18\x01 \x01(\fR\n" +
	"sessionTag\x124\n" +
	"\x06header\x18\x02 \x01(\v2\x1c.syncproto.SessionHeaderDataR\x06header\x12+\n" +
	"\x03tab\x18\x03 \x01(\v2\x19.syncproto.SessionTabDataR\x03tab\x12\x1e\n" +
	"\vtab_node_id\x18\x04 \x01(\x05R\ttabNodeId\"I\n" +
	"\vSyncSession\x12:\n" +
	"\asession\x18Ǉ\x03 \x01(\v2\x1e.syncproto.SessionSpecificsMsgR\asession\"n\n" +
	"\x14UserConsentSpecifics\x12\x1d\n" +
	"\n" +
	"account_id\x18\x06 \x01(\fR\taccountId\x127\n" +
	"\x18client_consent_time_usec\x18\f \x01(\x03R\x15clientConsentTimeUsec\"W\n" +
	"\x0fSyncUserConsent\x12D\n" +
	"\fuser_consent\x18\xee\xf7! \x01(\v2\x1f.syncproto.UserConsentSpecificsR\vuserConsent\"|\n" +
	"\x11GlobalIdDirective\x12\x1b\n" +
	"\tglobal_id\x18\x01 \x03(\x03R\bglobalId\x12&\n" +
	"\x0fstart_time_usec\x18\x02 \x01(\x03R\rstartTimeUsec\x12\"\n" +
	"\rend_time_usec\x18\x03 \x01(\x03R\vendTimeUsec\"`\n" +
	"\x12TimeRangeDirective\x12&\n" +
	"\x0fstart_time_usec\x18\x01 \x01(\x03R\rstartTimeUsec\x12\"\n" +
	"\rend_time_usec\x18\x02 \x01(\x03R\vendTimeUsec\"D\n" +
	"\fUrlDirective\x12\x10\n" +
	"\x03url\x18\x01 \x01(\fR\x03url\x12\"\n" +
	"\rend_time_usec\x18\x02 \x01(\x03R\vendTimeUsec\"\xfe\x01\n" +
	"\x1fHistoryDeleteDirectiveSpecifics\x12L\n" +
	"\x13global_id_directive\x18\x01 \x01(\v2\x1c.syncproto.GlobalIdDirectiveR\x11globalIdDirective\x12O\n" +
	"\x14time_range_directive\x18\x02 \x01(\v2\x1d.syncproto.TimeRangeDirectiveR\x12timeRangeDirective\x12<\n" +
	"\rurl_directive\x18\x03 \x01(\v2\x17.syncproto.UrlDirectiveR\furlDirective\"\x84\x01\n" +
	"\x1aSyncHistoryDeleteDirective\x12f\n" +
	"\x18history_delete_directive\x18\xeb\x95\t \x01(\v2*.syncproto.HistoryDeleteDirectiveSpecificsR\x16historyDeleteDirective\"Q\n" +
	"\x13NigoriEncryptedData\x12\x19\n" +
	"\bkey_name\x18\x01 \x01(\fR\akeyName\x12\x1f\n" +
	"\vcipher_text\x18\x02 \x01(\fR\n" +
	"cipherText\"\xb8\x04\n" +
	"\x0fNigoriSpecifics\x12K\n" +
	"\x11encryption_keybag\x18\x01 \x01(\v2\x1e.syncproto.NigoriEncryptedDataR\x10encryptionKeybag\x12(\n" +
	"\x10keybag_is_frozen\x18\x02 \x01(\bR\x0ekeybagIsFrozen\x12-\n" +
	"\x12encrypt_everything\x18\f \x01(\bR\x11encryptEverything\x12'\n" +
	"\x0fpassphrase_type\x18\r \x01(\x05R\x0epassphraseType\x126\n" +
	"\x17keystore_migration_time\x18\x0e \x01(\x03R\x15keystoreMigrationTime\x124\n" +
	"\x16custom_passphrase_time\x18\x10 \x01(\x03R\x14customPassphraseTime\x12T\n" +
	"'custom_passphrase_key_derivation_method\x18\x11 \x01(\x05R#customPassphraseKeyDerivationMethod\x12P\n" +
	"%custom_passphrase_key_derivation_salt\x18\x12 \x01(\fR!customPassphraseKeyDerivationSalt\x12@\n" +
	"\x1dcross_user_sharing_public_key\x18\x18 \x01(\fR\x19crossUserSharingPublicKey\"B\n" +
	"\n" +
	"SyncNigori\x124\n" +
	"\x06nigori\x18\x81\xf5\x02 \x01(\v2\x1a.syncproto.NigoriSpecificsR\x06nigori\"\xa0\x01\n" +
	"\x12EdgeEDropSpecifics\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\fR\x04guid\x12\x14\n" +
	"\x05title\x18\x02 \x01(\fR\x05title\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\fR\vcontentType\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12#\n" +
	"\rcreation_time\x18\x05 \x01(\x03R\fcreationTime\"P\n" +
	"\rSyncEdgeEDrop\x12?\n" +
	"\vedge_e_drop\x18Я: \x01(\v2\x1d.syncproto.EdgeEDropSpecificsR\tedgeEDropB\x1eZ\x1csynchole/syncproto;syncprotob\x06proto3"

var (
	file_extra_proto_rawDescOnce sync.Once
	file_extra_proto_rawDescData []byte
)

func file_extra_proto_rawDescGZIP() []byte {
	file_extra_proto_rawDescOnce.Do(func() {
		file_extra_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_extra_proto_rawDesc), len(file_extra_proto_rawDesc)))
	})
	return file_extra_proto_rawDescData
}

var file_extra_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_extra_proto_goTypes = []any{
	(*SendTabToSelfSpecifics)(nil),          // 0: syncproto.SendTabToSelfSpecifics
	(*SyncSendTabToSelf)(nil),               // 1: syncproto.SyncSendTabToSelf
	(*DeviceSyncedTypes)(nil),               // 2: syncproto.DeviceSyncedTypes
	(*DeviceInfoSpecifics)(nil),             // 3: syncproto.DeviceInfoSpecifics
	(*SyncDeviceInfo)(nil),                  // 4: syncproto.SyncDeviceInfo
	(*WebAppSpecifics)(nil),                 // 5: syncproto.WebAppSpecifics
	(*SyncWebApp)(nil),                      // 6: syncproto.SyncWebApp
	(*WebauthnCredentialSpecifics)(nil),     // 7: syncproto.WebauthnCredentialSpecifics
	(*SyncWebauthnCredential)(nil),          // 8: syncproto.SyncWebauthnCredential
	(*AutofillSpecifics)(nil),               // 9: syncproto.AutofillSpecifics
	(*SyncAutofill)(nil),                    // 10: syncproto.SyncAutofill
	(*AutofillProfileSpecifics)(nil),        // 11: syncproto.AutofillProfileSpecifics
	(*SyncAutofillProfile)(nil),             // 12: syncproto.SyncAutofillProfile
	(*SavedTabGroupData)(nil),               // 13: syncproto.SavedTabGroupData
	(*SavedTabGroupTab)(nil),                // 14: syncproto.SavedTabGroupTab
	(*SavedTabGroupSpecifics)(nil),          // 15: syncproto.SavedTabGroupSpecifics
	(*SyncSavedTabGroup)(nil),               // 16: syncproto.SyncSavedTabGroup
	(*SessionTabNavigation)(nil),            // 17: syncproto.SessionTabNavigation
	(*SessionTabData)(nil),                  // 18: syncproto.SessionTabData
	(*SessionWindowData)(nil),               // 19: syncproto.SessionWindowData
	(*SessionHeaderData)(nil),               // 20: syncproto.SessionHeaderData
	(*SessionSpecificsMsg)(nil),             // 21: syncproto.SessionSpecificsMsg
	(*SyncSession)(nil),                     // 22: syncproto.SyncSession
	(*UserConsentSpecifics)(nil),            // 23: syncproto.UserConsentSpecifics
	(*SyncUserConsent)(nil),                 // 24: syncproto.SyncUserConsent
	(*GlobalIdDirective)(nil),               // 25: syncproto.GlobalIdDirective
	(*TimeRangeDirective)(nil),              // 26: syncproto.TimeRangeDirective
	(*UrlDirective)(nil),                    // 27: syncproto.UrlDirective
	(*HistoryDeleteDirectiveSpecifics)(nil), // 28: syncproto.HistoryDeleteDirectiveSpecifics
	(*SyncHistoryDeleteDirective)(nil),      // 29: syncproto.SyncHistoryDeleteDirective
	(*NigoriEncryptedData)(nil),             // 30: syncproto.NigoriEncryptedData
	(*NigoriSpecifics)(nil),                 // 31: syncproto.NigoriSpecifics
	(*SyncNigori)(nil),                      // 32: syncproto.SyncNigori
	(*EdgeEDropSpecifics)(nil),              // 33: syncproto.EdgeEDropSpecifics
	(*SyncEdgeEDrop)(nil),                   // 34: syncproto.SyncEdgeEDrop
}
var file_extra_proto_depIdxs = []int32{
	0,  // 0: syncproto.SyncSendTabToSelf.send_tab_to_self:type_name -> syncproto.SendTabToSelfSpecifics
	2,  // 1: syncproto.DeviceInfoSpecifics.synced_types:type_name -> syncproto.DeviceSyncedTypes
	3,  // 2: syncproto.SyncDeviceInfo.device_info:type_name -> syncproto.DeviceInfoSpecifics
	5,  // 3: syncproto.SyncWebApp.web_app:type_name -> syncproto.WebAppSpecifics
	7,  // 4: syncproto.SyncWebauthnCredential.webauthn_credential:type_name -> syncproto.WebauthnCredentialSpecifics
	9,  // 5: syncproto.SyncAutofill.autofill:type_name -> syncproto.AutofillSpecifics
	11, // 6: syncproto.SyncAutofillProfile.autofill_profile:type_name -> syncproto.AutofillProfileSpecifics
	13, // 7: syncproto.SavedTabGroupSpecifics.group:type_name -> syncproto.SavedTabGroupData
	14, // 8: syncproto.SavedTabGroupSpecifics.tab:type_name -> syncproto.SavedTabGroupTab
	15, // 9: syncproto.SyncSavedTabGroup.saved_tab_group:type_name -> syncproto.SavedTabGroupSpecifics
	17, // 10: syncproto.SessionTabData.navigation:type_name -> syncproto.SessionTabNavigation
	19, // 11: syncproto.SessionHeaderData.window:type_name -> syncproto.SessionWindowData
	20, // 12: syncproto.SessionSpecificsMsg.header:type_name -> syncproto.SessionHeaderData
	18, // 13: syncproto.SessionSpecificsMsg.tab:type_name -> syncproto.SessionTabData
	21, // 14: syncproto.SyncSession.session:type_name -> syncproto.SessionSpecificsMsg
	23, // 15: syncproto.SyncUserConsent.user_consent:type_name -> syncproto.UserConsentSpecifics
	25, // 16: syncproto.HistoryDeleteDirectiveSpecifics.global_id_directive:type_name -> syncproto.GlobalIdDirective
	26, // 17: syncproto.HistoryDeleteDirectiveSpecifics.time_range_directive:type_name -> syncproto.TimeRangeDirective
	27, // 18: syncproto.HistoryDeleteDirectiveSpecifics.url_directive:type_name -> syncproto.UrlDirective
	28, // 19: syncproto.SyncHistoryDeleteDirective.history_delete_directive:type_name -> syncproto.HistoryDeleteDirectiveSpecifics
	30, // 20: syncproto.NigoriSpecifics.encryption_keybag:type_name -> syncproto.NigoriEncryptedData
	31, // 21: syncproto.SyncNigori.nigori:type_name -> syncproto.NigoriSpecifics
	33, // 22: syncproto.SyncEdgeEDrop.edge_e_drop:type_name -> syncproto.EdgeEDropSpecifics
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_extra_proto_init() }
func file_extra_proto_init() {
	if File_extra_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_extra_proto_rawDesc), len(file_extra_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_extra_proto_goTypes,
		DependencyIndexes: file_extra_proto_depIdxs,
		MessageInfos:      file_extra_proto_msgTypes,
	}.Build()
	File_extra_proto = out.File
	file_extra_proto_goTypes = nil
	file_extra_proto_depIdxs = nil
}
